name: Mi workflow

on: push 

jobs:
  tareas:
    runs-on: ubuntu-latest
    permissions:
     security-events: write
    steps: 

      - name: Bajar código
        uses: actions/checkout@v4

      - name: Comprobar calidad del codigo
        uses: advanced-security/python-lint-code-scanning-action@v1
        with: 
          linter: pylint
          
        
